### ISSUE TITLE
generte sample dataset

### ISSUE THREAD

**Issue by serendipityshe** [TonyXuQAQ/RNGDetPlusPlus#29]
run main_sample.py tranceback, please help me!

Traceback (most recent call last):
  File "d:\PROJECT\AI-Project\Segmentanction\RNGDetPlusPlus\spacenet\main_sample.py", line 110, in <module>
    BC_sample(args)
  File "d:\PROJECT\AI-Project\Segmentanction\RNGDetPlusPlus\spacenet\main_sample.py", line 40, in BC_sample
    np.savez(os.path.join(f'./{args.savedir}/samples/{sample_tag}',f'{tile_name}_{sampler.step_counter}.npz'),sat=sat_ROI.astype(np.uint8),label_masks=label_masks_ROI.astype(np.uint8),\
  File "E:\anaconda3\envs\yolov8\Lib\site-packages\numpy\lib\npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "E:\anaconda3\envs\yolov8\Lib\site-packages\numpy\lib\npyio.py", line 740, in _savez
    val = np.asanyarray(val)
          ^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**Comment by Yu-zhengbo** [comment]
You can change the code Line 40-41 in main_sample.py  to "            np.savez(os.path.join(f'./{args.savedir}/samples/{sample_tag}',f'{tile_name}_{sampler.step_counter}.npz'),sat=sat_ROI.astype(np.uint8),label_masks=label_masks_ROI.astype(np.uint8),\
             historical_ROI=historical_ROI.astype(np.uint8),gt_probs=gt_probs,gt_coords=gt_coords,list_len=list_len,ahead_segments=np.array(ahead_segments,dtype=object))". The reason of this error is the ahead_segments have different shape, but the np.savez will use the np.array(ahead_segments), so you can change the type of ahead_segments to object before np.savez, so the error is fixed.
